Please, check homework1
harina9/homework-repository-1 pull request #1
Opened 2021-04-17 20:21 UTC by harina9

2021-04-22 08:23 UTC, Chanterz requested changes
Есть несколько замечаний

2021-04-22 08:23 UTC, Chanterz commented on homework1/task3.py
> +            new_list.append(value)
А зачем ты собираешь в массив числа? Подумай над тем, как это сделать прямо в цикле, без сохранения в массив

2021-04-22 08:23 UTC, Chanterz commented on tests/homework1/test_task2.py
> +    assert check_fibonacci([56, 78, -10])
Тебе вот даже гитхаб показывает, что не хватает пустой строки в конце файла :)

2021-04-22 08:23 UTC, Chanterz commented on homework1/task5.py
> +    return maximum
Эту задачку можно решить сильно проще и читаемее
Ты тут уже используешь срезы, но подумай, как можно было бы их использовать, чтобы лишний раз их все не хранить в памяти

2021-04-23 19:06 UTC, harina9 commented on tests/homework1/test_task2.py
> +    assert check_fibonacci([56, 78, -10])
Вот тут немного не поняла, что именно нужно подправить)

2021-04-28 08:15 UTC, Chanterz requested changes
Нужно исправить отсутствие пустых строк в конце файла и ещё пара замечаний по функциональности

2021-04-28 08:15 UTC, Chanterz commented on homework1/task2.py
> +    for our_number, fib_number in zip(data, generate_fibonacci(5)):
При таком подход на очень больших последовательностях программа будет падать

2021-04-28 08:15 UTC, Chanterz commented on homework1/task3.py
> +        return minimum, maximum
Не хватает пустой строки в конце файла

2021-04-28 08:15 UTC, Chanterz commented on homework1/task5.py
> +print(find_maximal_subarray_sum([-3, -10, -7, -7], 3))
Здесь тоже не хватает пустой строки

2021-04-28 08:15 UTC, Chanterz commented on tests/homework1/test_task3.py
> +    assert find_maximum_and_minimum('number3.txt') == (-19, 78)
Ты вообще смотрела свой пулл-реквест? Не смутили эти сообщения от гитхаба? :)

2021-04-28 08:15 UTC, Chanterz commented on homework1/task5.py
> +    max_sum = float('inf')
Тут точно `inf`, а не `-inf`?

2021-04-28 08:46 UTC, harina9 commented on tests/homework1/test_task3.py
> +    assert find_maximum_and_minimum('number3.txt') == (-19, 78)
Я в упор не вижу никаких сообщений и не знаю, где их смотреть)

2021-04-28 08:47 UTC, harina9 commented on homework1/task5.py
> +print(find_maximal_subarray_sum([-3, -10, -7, -7], 3))
То есть мне каждый раз просто нужно добавлять пустую строку самостоятельно? У меня так и не работает проверка на black и isort тут, и я не знаю, как ее подключить

2021-04-28 08:48 UTC, harina9 commented on homework1/task5.py
> +    max_sum = float('inf')
Здесь да, согласна

2021-04-28 08:49 UTC, Chanterz commented on tests/homework1/test_task2.py
> +    assert check_fibonacci([56, 78, -10])
Просто во всех файлах последняя строка должна быть пустой

2021-04-28 08:50 UTC, Chanterz commented on tests/homework1/test_task3.py
> +    assert find_maximum_and_minimum('number3.txt') == (-19, 78)
Когда смотришь все свои изменения в пулл-реквесте гитхаб прямо красными кружками подсвечивает это)

2021-04-28 08:51 UTC, Chanterz commented on homework1/task5.py
> +print(find_maximal_subarray_sum([-3, -10, -7, -7], 3))
Ну проходись black локально, например

2021-04-28 11:07 UTC, harina9 commented on tests/homework1/test_task2.py
> +    assert check_fibonacci([56, 78, -10])
Подправила строки везде

2021-05-01 08:14 UTC, harina9 commented on homework1/task5.py
> +    max_sum = float('inf')
Ой, да, точно

2021-05-07 09:33 UTC, Chanterz approved these changes

2021-06-01 14:44 UTC, merged