Please, check homework2
harina9/homework-repository-1 pull request #2
Opened 2021-04-25 13:30 UTC by harina9

2021-04-28 08:36 UTC, Chanterz requested changes

2021-04-28 08:36 UTC, Chanterz commented on homework2/task1.py
> +    list_every_char.sort(key=lambda i: i[1])
А что будет быстрее: найти минимум или отсортировать? Потому что `min` со сложными коллекциями умеет работать, ему только для этого функцию передать, которая из элемента получит ключ сравнения
<img width="832" alt="image" src="https://user-images.githubusercontent.com/15184609/116371598-44ae0680-a814-11eb-9594-6d3cd9af19af.png">

2021-04-28 08:36 UTC, Chanterz commented on homework2/task1.py
> +    list_d.sort(key=lambda i: i[1])
Здесь то же самое с минимумом

2021-04-28 08:36 UTC, Chanterz commented on homework2/task4.py
> +    stored_values = []
Тут ведь логичнее использовать словарь

2021-04-28 08:36 UTC, Chanterz commented on homework2/task5.py
> +
Зачем так много пустого места в конце файла?

2021-04-28 08:36 UTC, Chanterz commented on tests/homework2/test_task1.py
> +    assert get_longest_diverse_words('data.txt') == ['Nichtkämpfern', 'Entscheidungsschlacht', 'Schöpfungsmacht', 'Werkstättenlandschaft', 'Schicksalsfiguren', 'politisch-strategischen', 'Selbstverst
Длина строки должна быть не более 80 символов

2021-04-28 13:22 UTC, harina9 commented on homework2/task4.py
> +    stored_values = []
А если в аргументах функции будут нехэшируемые элементы?

2021-04-28 17:32 UTC, harina9 commented on homework2/task1.py
> +    list_every_char.sort(key=lambda i: i[1])
Как я поняла, у sort() сложность O(n logn), а у min(), max() - О(n), значит второй вариант более выигрышный) Сейчас подправлю

2021-05-07 09:38 UTC, Chanterz commented on homework2/task4.py
> +    stored_values = []
Тоже верно. Но это тоже обойти можно, но ладно, пусть будет так)

2021-05-07 09:40 UTC, Chanterz commented on tests/homework2/test_task4.py
> +def test_cache_function():
Этот кейс правильный, но по идее нужно было бы ещё один, который проверяет, что обёрнутая в декоратор функция второй раз не вызывается

2021-05-07 09:40 UTC, Chanterz approved these changes

2021-06-15 12:26 UTC, merged